//go:build go1.22

// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerURLHTTPSAPIWhistVamaryFr defines the Server URL for https://api.whist.vamary.fr
const ServerURLHTTPSAPIWhistVamaryFr = "https://api.whist.vamary.fr"

// Defines values for LobbyStatus.
const (
	Playing LobbyStatus = "playing"
	Waiting LobbyStatus = "waiting"
)

// Valid indicates whether the value is a known member of the LobbyStatus enum.
func (e LobbyStatus) Valid() bool {
	switch e {
	case Playing:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code" yaml:"code"`
	Message string `json:"message" yaml:"message"`
}

// Lobby defines model for Lobby.
type Lobby struct {
	CreatedAt time.Time          `json:"created_at" yaml:"created_at"`
	ID        openapi_types.UUID `json:"id" yaml:"id"`

	// JoinCode Short alphanumeric code players can share to join the lobby.
	JoinCode string             `json:"join_code" yaml:"join_code"`
	Members  []Member           `json:"members" yaml:"members"`
	OwnerID  openapi_types.UUID `json:"owner_id" yaml:"owner_id"`
	Status   LobbyStatus        `json:"status" yaml:"status"`
}

// LobbyStatus defines model for Lobby.Status.
type LobbyStatus string

// Member defines model for Member.
type Member struct {
	JoinedAt time.Time          `json:"joined_at" yaml:"joined_at"`
	UserID   openapi_types.UUID `json:"user_id" yaml:"user_id"`
	Username string             `json:"username" yaml:"username"`
}

// JoinLobbyJSONBody defines parameters for JoinLobby.
type JoinLobbyJSONBody struct {
	JoinCode string `json:"join_code" yaml:"join_code"`
}

// JoinLobbyJSONRequestBody defines body for JoinLobby for application/json ContentType.
type JoinLobbyJSONRequestBody JoinLobbyJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateLobby Create a lobby
	// (POST /lobbies)
	CreateLobby(w http.ResponseWriter, r *http.Request)
	// DestroyLobby Destroy a lobby
	// (DELETE /lobbies/{lobbyId})
	DestroyLobby(w http.ResponseWriter, r *http.Request, lobbyID openapi_types.UUID)
	// GetLobby Get lobby state
	// (GET /lobbies/{lobbyId})
	GetLobby(w http.ResponseWriter, r *http.Request, lobbyID openapi_types.UUID)
	// StartGame Start the game
	// (POST /lobbies/{lobbyId}/game)
	StartGame(w http.ResponseWriter, r *http.Request, lobbyID openapi_types.UUID)
	// JoinLobby Join a lobby
	// (POST /lobbies/{lobbyId}/members)
	JoinLobby(w http.ResponseWriter, r *http.Request, lobbyID openapi_types.UUID)
	// LeaveLobby Leave a lobby
	// (DELETE /lobbies/{lobbyId}/members/me)
	LeaveLobby(w http.ResponseWriter, r *http.Request, lobbyID openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateLobby operation middleware
func (siw *ServerInterfaceWrapper) CreateLobby(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLobby(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DestroyLobby operation middleware
func (siw *ServerInterfaceWrapper) DestroyLobby(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "lobbyId" -------------
	var lobbyID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "lobbyId", r.PathValue("lobbyId"), &lobbyID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lobbyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DestroyLobby(w, r, lobbyID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLobby operation middleware
func (siw *ServerInterfaceWrapper) GetLobby(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "lobbyId" -------------
	var lobbyID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "lobbyId", r.PathValue("lobbyId"), &lobbyID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lobbyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLobby(w, r, lobbyID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartGame operation middleware
func (siw *ServerInterfaceWrapper) StartGame(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "lobbyId" -------------
	var lobbyID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "lobbyId", r.PathValue("lobbyId"), &lobbyID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lobbyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartGame(w, r, lobbyID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinLobby operation middleware
func (siw *ServerInterfaceWrapper) JoinLobby(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "lobbyId" -------------
	var lobbyID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "lobbyId", r.PathValue("lobbyId"), &lobbyID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lobbyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinLobby(w, r, lobbyID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LeaveLobby operation middleware
func (siw *ServerInterfaceWrapper) LeaveLobby(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "lobbyId" -------------
	var lobbyID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "lobbyId", r.PathValue("lobbyId"), &lobbyID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lobbyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeaveLobby(w, r, lobbyID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/lobbies", wrapper.CreateLobby)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/lobbies/{lobbyId}", wrapper.DestroyLobby)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/lobbies/{lobbyId}", wrapper.GetLobby)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/lobbies/{lobbyId}/members", wrapper.JoinLobby)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/lobbies/{lobbyId}/members/me", wrapper.LeaveLobby)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/lobbies/{lobbyId}/game", wrapper.StartGame)

	return m
}

type CreateLobbyRequestObject struct {
}

type CreateLobbyResponseObject interface {
	VisitCreateLobbyResponse(w http.ResponseWriter) error
}

type CreateLobby201JSONResponse Lobby

func (response CreateLobby201JSONResponse) VisitCreateLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLobby403JSONResponse Error

func (response CreateLobby403JSONResponse) VisitCreateLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DestroyLobbyRequestObject struct {
	LobbyID openapi_types.UUID `json:"lobbyId"`
}

type DestroyLobbyResponseObject interface {
	VisitDestroyLobbyResponse(w http.ResponseWriter) error
}

type DestroyLobby202Response struct {
}

func (response DestroyLobby202Response) VisitDestroyLobbyResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type DestroyLobby403JSONResponse Error

func (response DestroyLobby403JSONResponse) VisitDestroyLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DestroyLobby404JSONResponse Error

func (response DestroyLobby404JSONResponse) VisitDestroyLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetLobbyRequestObject struct {
	LobbyID openapi_types.UUID `json:"lobbyId"`
}

type GetLobbyResponseObject interface {
	VisitGetLobbyResponse(w http.ResponseWriter) error
}

type GetLobby200JSONResponse Lobby

func (response GetLobby200JSONResponse) VisitGetLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLobby404JSONResponse Error

func (response GetLobby404JSONResponse) VisitGetLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StartGameRequestObject struct {
	LobbyID openapi_types.UUID `json:"lobbyId"`
}

type StartGameResponseObject interface {
	VisitStartGameResponse(w http.ResponseWriter) error
}

type StartGame202Response struct {
}

func (response StartGame202Response) VisitStartGameResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type StartGame403JSONResponse Error

func (response StartGame403JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StartGame404JSONResponse Error

func (response StartGame404JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StartGame409JSONResponse Error

func (response StartGame409JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type JoinLobbyRequestObject struct {
	LobbyID openapi_types.UUID `json:"lobbyId"`
	Body    *JoinLobbyJSONRequestBody
}

type JoinLobbyResponseObject interface {
	VisitJoinLobbyResponse(w http.ResponseWriter) error
}

type JoinLobby200JSONResponse Lobby

func (response JoinLobby200JSONResponse) VisitJoinLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type JoinLobby403JSONResponse Error

func (response JoinLobby403JSONResponse) VisitJoinLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type JoinLobby404JSONResponse Error

func (response JoinLobby404JSONResponse) VisitJoinLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type JoinLobby409JSONResponse Error

func (response JoinLobby409JSONResponse) VisitJoinLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type LeaveLobbyRequestObject struct {
	LobbyID openapi_types.UUID `json:"lobbyId"`
}

type LeaveLobbyResponseObject interface {
	VisitLeaveLobbyResponse(w http.ResponseWriter) error
}

type LeaveLobby204Response struct {
}

func (response LeaveLobby204Response) VisitLeaveLobbyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LeaveLobby404JSONResponse Error

func (response LeaveLobby404JSONResponse) VisitLeaveLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateLobby Create a lobby
	// (POST /lobbies)
	CreateLobby(ctx context.Context, request CreateLobbyRequestObject) (CreateLobbyResponseObject, error)
	// DestroyLobby Destroy a lobby
	// (DELETE /lobbies/{lobbyId})
	DestroyLobby(ctx context.Context, request DestroyLobbyRequestObject) (DestroyLobbyResponseObject, error)
	// GetLobby Get lobby state
	// (GET /lobbies/{lobbyId})
	GetLobby(ctx context.Context, request GetLobbyRequestObject) (GetLobbyResponseObject, error)
	// StartGame Start the game
	// (POST /lobbies/{lobbyId}/game)
	StartGame(ctx context.Context, request StartGameRequestObject) (StartGameResponseObject, error)
	// JoinLobby Join a lobby
	// (POST /lobbies/{lobbyId}/members)
	JoinLobby(ctx context.Context, request JoinLobbyRequestObject) (JoinLobbyResponseObject, error)
	// LeaveLobby Leave a lobby
	// (DELETE /lobbies/{lobbyId}/members/me)
	LeaveLobby(ctx context.Context, request LeaveLobbyRequestObject) (LeaveLobbyResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateLobby operation middleware
func (sh *strictHandler) CreateLobby(w http.ResponseWriter, r *http.Request) {
	var request CreateLobbyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateLobby(ctx, request.(CreateLobbyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateLobby")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateLobbyResponseObject); ok {
		if err := validResponse.VisitCreateLobbyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DestroyLobby operation middleware
func (sh *strictHandler) DestroyLobby(w http.ResponseWriter, r *http.Request, lobbyID openapi_types.UUID) {
	var request DestroyLobbyRequestObject

	request.LobbyID = lobbyID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DestroyLobby(ctx, request.(DestroyLobbyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DestroyLobby")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DestroyLobbyResponseObject); ok {
		if err := validResponse.VisitDestroyLobbyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLobby operation middleware
func (sh *strictHandler) GetLobby(w http.ResponseWriter, r *http.Request, lobbyID openapi_types.UUID) {
	var request GetLobbyRequestObject

	request.LobbyID = lobbyID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLobby(ctx, request.(GetLobbyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLobby")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLobbyResponseObject); ok {
		if err := validResponse.VisitGetLobbyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartGame operation middleware
func (sh *strictHandler) StartGame(w http.ResponseWriter, r *http.Request, lobbyID openapi_types.UUID) {
	var request StartGameRequestObject

	request.LobbyID = lobbyID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartGame(ctx, request.(StartGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartGameResponseObject); ok {
		if err := validResponse.VisitStartGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// JoinLobby operation middleware
func (sh *strictHandler) JoinLobby(w http.ResponseWriter, r *http.Request, lobbyID openapi_types.UUID) {
	var request JoinLobbyRequestObject

	request.LobbyID = lobbyID

	var body JoinLobbyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.JoinLobby(ctx, request.(JoinLobbyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JoinLobby")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(JoinLobbyResponseObject); ok {
		if err := validResponse.VisitJoinLobbyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LeaveLobby operation middleware
func (sh *strictHandler) LeaveLobby(w http.ResponseWriter, r *http.Request, lobbyID openapi_types.UUID) {
	var request LeaveLobbyRequestObject

	request.LobbyID = lobbyID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LeaveLobby(ctx, request.(LeaveLobbyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LeaveLobby")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LeaveLobbyResponseObject); ok {
		if err := validResponse.VisitLeaveLobbyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fhbb9u4Ev4rA57zcA6g2Lm1u/Wb06SBs2lSxCmy2W4Q0NLIYiORKkk5NQL/98WQujlW1kmbNsBinyyL",
	"1Fy/+TjDOxaqLFcSpTVscMdMmGDG3eOB1krTQ65VjtoKdK9DFSH92nmObMCM1UJO2SJgGRrDp11ri4Bp",
	"/FIIjREbfPISmv1XQbVfTT5jaEnWsZpM5h26NXKL0TW39C9WOqMnFnGLG1ZkyGpRjVkior34lWd5Sit8",
	"a7Id7kS7G/gqfr3xy69vNjf4JIw2MN7a3tl99ZresKARXhQi6pL7WQl5XQUjQhNqkVuhJBuwcaK0BZ7m",
	"CZdFhlqEQBshT/kctYGQSzAJ1whWAckBmyCk5HOPBS1bL36//GN3u0t7htkEtQuKsJi5h/9qjNmA/aff",
	"pLRf5rP/3u1ni1oU15rP6b+6laivfZTWOm0st4VThrLIKJm3XFhaDBh5R09XwZr8O9FN+Fom1AoaB4N2",
	"0rugUnq2ghVS8ESoFObxkaC9kmePgHsltfVN0LJu1SeKM4aFFnY+pvR5fybINephYZPm37vKyqOLcwqe",
	"280G5WpjdmJtzhYkWMhYrQL27GB8DsMPI4iVhoxLPhVyCheJMBamPPPYFGiAywgMGiOUNARVK6wHqts6",
	"/DBiAZuhNl7sdm+zt+kwlqPkuWADttPb6lF55dwmzq1+KZqec2XsqnFvXf4NcJB4W1YJnCcIvLAJSitC",
	"ggdQcGGCocrQuHpyqCIjCRWchI2iWpwnGEqUyZU0Xv/25pZnOGlROkt4nqckXyjZ/2yUbChyXcF5BS7m",
	"y+64BShBDaYIQzQmLtJ03qNQ7W7uPMKGmiIqPmbD47OD4f7l9ejk+vh0b++yRbADdqkKyApjIUU+Q5ir",
	"QkNYaI3S+oDCBGOl0ZtFuffBVhKdUY9z2R8YHS5/pNQIAzzVyKM5CAm8ojvabYos43peJ6dadYsVQPp3",
	"7t0oWniIpGg7qPc3Ed6QohRKAnGQ9btNi2bhVKbz5r8HC2R8DiF9bBNhenCGPHVkATcivAGckbtAvB0J",
	"k3MbJhiBVbWqmeBwgZOxCm/QViF1uoWSvT/lChb30Vit5g+AcXvVPbcTIvqsCOkd8DDE3GLUg/elFbci",
	"TUFjiGJGkWxMX7bvu9D27vRsb7S/f3CyBLPOmNJhF3k/QdjngNNbnqYeUFLZ+/pKt3a/yS1XOdcnp+fX",
	"704/nuwvOXeiSjX4VRhLYbaJwwmM9p/DK59a8ihWhYzuV0YJlaY0AjbFDrY8Q1to6aFelTgdqggqbmIV",
	"gJBhWkRU6sKapWLxR/AqcR6ifQComz+LNavI/CMzfIgVGbt8kcKca56hdY3epzsmSAqdnCxgvvdgJSey",
	"dsthdYFtY9f0MourTpbtT8vu5icZETxw/I+ksIJX7N3qSahXcdl5AqMf0oclj/8vQp4G4MolABMqjeb/",
	"HezePkyWGbSD0ceWa3voe7z1dO7MMfRJi8cPvHmOxidLxrwYf3sTaYUi/y+HP77CyY833+TH4fD9gXNj",
	"fD48Ox/uHR+stHQSMQLuujpjYbeeL62qQNWql+fw70RZQKmKaVLpCkDpGhiQ8KbJcxbgCsuNl6D0QIfX",
	"b423L0w/wyjyzNMxbVjVQi65XvLE6tl5pIRsDs8vBRq7p6L5k87N1fG2vn5Yf2NwbyZtvu4YPxf3A7l4",
	"iRN/3JqMwI/L7WuSFx+VyCQ3KUllk5KzfuSc9IMZ0RFWc6aSd+7S6gfQIlFGLZ/8FXLGU/F9dNk4eXQ6",
	"Olmhy/O6UfBnDqRKTlGXxy7lkebdktSez2dhgAD8VJI8Uk3q11BkP8O/m4fPMFMzfJDBYq2y9lQ88jNC",
	"UQKxvkYJ/I9JRO7eay5NjFqXHZIvgYr9SIpspmKNGRcyaNSQBG9vRDapjJNNdAHS0VAdUxk+MHfsdly9",
	"tlkjxdiucMa31RAB60G+oJ6R0F3xvx+1hGnpfd4Kqk/dKlH3tbtBewlSLo7t6fFnzRat20ynqH2P+emK",
	"Dl6DelaZUei0vK80g36f56J3Sx1Mb8bJj16s2eJq8dcA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
